import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export async function exportReportAsPDF(result, elementId) {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Header
  pdf.setFillColor(10, 15, 30);
  pdf.rect(0, 0, pageWidth, 40, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(20);
  pdf.setFont("helvetica", "bold");
  pdf.text("LakshyaAI", margin, 18);
  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(150, 150, 180);
  pdf.text("Plagiarism Detection Report", margin, 27);
  pdf.setTextColor(100, 100, 130);
  pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, 34);
  y = 55;

  // Document info
  pdf.setTextColor(30, 30, 30);
  pdf.setFontSize(13);
  pdf.setFont("helvetica", "bold");
  pdf.text("Document Information", margin, y);
  y += 8;
  pdf.setDrawColor(200, 200, 220);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(60, 60, 80);
  pdf.text("Document:", margin, y);
  pdf.setTextColor(30, 30, 30);
  pdf.text(`${result.document}`, margin + 30, y);
  y += 7;

  pdf.setTextColor(60, 60, 80);
  pdf.text("Detection Mode:", margin, y);
  pdf.setTextColor(30, 30, 30);
  pdf.text(`${result.mode.toUpperCase()}`, margin + 30, y);
  y += 7;

  pdf.setTextColor(60, 60, 80);
  pdf.text("Top Match:", margin, y);
  pdf.setTextColor(30, 30, 30);
  pdf.text(`${result.top_match || "None"}`, margin + 30, y);
  y += 14;

  // Score
  pdf.setFontSize(13);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(30, 30, 30);
  pdf.text("Similarity Score", margin, y);
  y += 8;
  pdf.setDrawColor(200, 200, 220);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 10;

  const score = result.top_similarity;
  const scoreColor = score >= 70 ? [239, 68, 68] : score >= 40 ? [249, 115, 22] : [34, 197, 94];
  const riskLabel = score >= 70 ? "HIGH RISK" : score >= 40 ? "MODERATE RISK" : "LOW RISK";

  pdf.setFillColor(...scoreColor);
  pdf.roundedRect(margin, y, 60, 20, 4, 4, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(16);
  pdf.setFont("helvetica", "bold");
  pdf.text(`${score}%`, margin + 10, y + 13);

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...scoreColor);
  pdf.text(riskLabel, margin + 68, y + 13);
  y += 30;

  // Match table
  pdf.setFontSize(13);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(30, 30, 30);
  pdf.text("Matched Sources", margin, y);
  y += 8;
  pdf.setDrawColor(200, 200, 220);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  pdf.setFillColor(240, 240, 250);
  pdf.rect(margin, y, pageWidth - margin * 2, 8, "F");
  pdf.setFontSize(9);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(60, 60, 80);
  pdf.text("Source Document", margin + 3, y + 5.5);
  pdf.text("Type", pageWidth - margin - 50, y + 5.5);
  pdf.text("Similarity", pageWidth - margin - 20, y + 5.5);
  y += 10;

  result.matches.forEach((match, i) => {
    if (y > 260) { pdf.addPage(); y = margin; }
    const rowColor = i % 2 === 0 ? [255, 255, 255] : [248, 248, 252];
    pdf.setFillColor(...rowColor);
    pdf.rect(margin, y, pageWidth - margin * 2, 7, "F");
    pdf.setFontSize(8.5);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(30, 30, 30);
    const name = match.filename.length > 55 ? match.filename.slice(0, 55) + "..." : match.filename;
    pdf.text(name, margin + 3, y + 5);
    pdf.text(match.source_type || "file", pageWidth - margin - 50, y + 5);
    const sc = match.similarity;
    const c = sc >= 70 ? [239, 68, 68] : sc >= 40 ? [249, 115, 22] : [34, 197, 94];
    pdf.setTextColor(...c);
    pdf.setFont("helvetica", "bold");
    pdf.text(`${match.similarity}%`, pageWidth - margin - 20, y + 5);
    y += 7;
  });

  y += 10;

  // Capture chart
  const chartEl = document.getElementById(elementId);
  if (chartEl) {
    try {
      const canvas = await html2canvas(chartEl, { backgroundColor: "#0f1629", scale: 2 });
      const imgData = canvas.toDataURL("image/png");
      if (y + 80 > 270) { pdf.addPage(); y = margin; }
      pdf.setFontSize(13);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(30, 30, 30);
      pdf.text("Similarity Chart", margin, y);
      y += 6;
      pdf.addImage(imgData, "PNG", margin, y, pageWidth - margin * 2, 70);
    } catch (e) {
      console.warn("Chart capture failed", e);
    }
  }

  // Footer
  pdf.setFontSize(8);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(150, 150, 170);
  pdf.text("Generated by LakshyaAI — lackilohar.netlify.app", margin, 285);

  pdf.save(`plagiarism-report-${result.document.replace(/[^a-z0-9]/gi, "_")}.pdf`);
}
